[package]
name = "RustSPARQL"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
oxigraph = "0.2.5"
datafrog = "2.0.1"
rio_turtle = "0.7.1"
rio_api = "0.7.1"